export const REGISTER_LOADING = "REGISTER_LOADING";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const AUTH_ACTION = "AUTH_ACTION";
export const FETCH_ALL_CURRENCIES = "FETCH_ALL_CURRENCIES";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const HANDLE_LOGIN_ERRORS = "HANDLE_LOGIN_ERRORS";
export const HANDLE_SIGNUP_ERRORS = "HANDLE_SIGNUP_ERRORS";
